language: python
dist: bionic
cache:
  pip: true
  directories:
    - $HOME/nest-$NEST_VERSION
    - $HOME/.cache/pre-commit
jobs:
  include:
      python: 3.8
      before_install:
        - export NEST_INSTALL_DIR=/home/travis/nest-$NEST_VERSION
        - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
        - sudo dpkg -i nrn-7.7.x86_64-linux.deb
        - export PYTHONPATH=/usr/local/nrn/lib/python:$PYTHONPATH
install:
  - source devops/check_nest_cache.sh
  - sudo apt-get install -y python3-rtree build-essential cmake cython libgsl-dev libltdl-dev libncurses-dev libreadline-dev openmpi-bin libopenmpi-dev
  - if [ "$HAS_NEST_CACHE" = "0" ]; then
      source devops/install_nest.sh
    else
      echo "NEST cache found, skipping installation";
    fi
  - if [ "$HAS_CEREBNEST_CACHE" = "0" ]; then
      source devops/install_nest_modules.sh
    else
      echo "CEREBNEST cache found, skipping installation";
    fi
  - source devops/post_install_env_vars.sh
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install -e .
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
